name: mmenv
channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - matplotlib
    - dill
    - pandas
    - mkl-service
    - theano
    - patsy
    - arviz
    - python-graphviz
    - pymc3
    - pdf2image
    - seaborn
    - poppler
